
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    # Port exposed for direct access if needed
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_PORT=${BACKEND_PORT}
      - DJANGO_SETTINGS_MODULE=storyteller_backend.dev_settings
    networks:
      - storyteller_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Port exposed for direct access if needed
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_HOST=${BACKEND_HOST}
      - VITE_BACKEND_PORT=${BACKEND_PORT}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - storyteller_network

networks:
  storyteller_network: