export enum IdeaType {
  CHARACTER = 'CHARACTER',
  PLACE = 'PLACE',
  ITEM = 'ITEM',
  SCENE = 'SCENE',
  CONFLICT = 'CONFLICT',
  DIALOGUE = 'DIALOGUE',
  CONCEPT = 'CONCEPT',
  WORLD_DETAIL = 'WORLD_DETAIL',
  PLOT_TWIST = 'PLOT_TWIST'
}
