name: StoryTeller Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
    
    - name: Start containers and run migrations
      run: docker compose up -d --wait --build
    
    - name: Run backend tests
      run: docker compose exec -T backend pytest
    
    - name: Run frontend tests
      run: docker compose exec -T frontend npm test
    
    - name: Stop containers
      if: always()
      run: docker compose down
